on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Run maven build
        run: mvn clean package -DskipTests
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - run: mvn test
  push_to_registry:
    name: push docker image to hub
    needs: [build, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: charlierthemis/devops-tp-4:main

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run maven test
        run: mvn javadoc:javadoc
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install netlify-cli -g
      - run: netlify deploy --prod --dir target/reports/apidocs --auth ${{secrets.NETLIFY_PASSWORD}} --site ${{secrets.NETLIFY_SITE_ID}}
